<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
            ['name' => 'Distrito Nacional', 'country_id' => 65],
            ['name' => 'Azua de Compostela', 'country_id' => 65],
            ['name' => 'Estebanía', 'country_id' => 65],
            ['name' => 'Guayabal', 'country_id' => 65],
            ['name' => 'Las Charcas', 'country_id' => 65],
            ['name' => 'Las Yayas de Viajama', 'country_id' => 65],
            ['name' => 'Padre Las Casas', 'country_id' => 65],
            ['name' => 'Peralta', 'country_id' => 65],
            ['name' => 'Pueblo Viejo', 'country_id' => 65],
            ['name' => 'Sabana Yegua', 'country_id' => 65],
            ['name' => 'Tábara Arriba', 'country_id' => 65],
            ['name' => 'Neiba', 'country_id' => 65],
            ['name' => 'Galván', 'country_id' => 65],
            ['name' => 'Los Ríos', 'country_id' => 65],
            ['name' => 'Tamayo', 'country_id' => 65],
            ['name' => 'Villa Jaragua', 'country_id' => 65],
            ['name' => 'Barahona', 'country_id' => 65],
            ['name' => 'Cabral', 'country_id' => 65],
            ['name' => 'El Peñón', 'country_id' => 65],
            ['name' => 'Enriquillo', 'country_id' => 65],
            ['name' => 'Fundación', 'country_id' => 65],
            ['name' => 'Jaquimeyes', 'country_id' => 65],
            ['name' => 'La Ciénaga', 'country_id' => 65],
            ['name' => 'Las Salinas', 'country_id' => 65],
            ['name' => 'Paraíso', 'country_id' => 65],
            ['name' => 'Polo', 'country_id' => 65],
            ['name' => 'Vicente Noble', 'country_id' => 65],
            ['name' => 'Dajabón', 'country_id' => 65],
            ['name' => 'El Pino', 'country_id' => 65],
            ['name' => 'Loma de Cabrera', 'country_id' => 65],
            ['name' => 'Partido', 'country_id' => 65],
            ['name' => 'Restauración', 'country_id' => 65],
            ['name' => 'San Francisco de Macorís', 'country_id' => 65],
            ['name' => 'Arenoso', 'country_id' => 65],
            ['name' => 'Castillo', 'country_id' => 65],
            ['name' => 'Eugenio María de Hostos', 'country_id' => 65],
            ['name' => 'Las Guáranas', 'country_id' => 65],
            ['name' => 'Pimentel', 'country_id' => 65],
            ['name' => 'Villa Riva', 'country_id' => 65],
            ['name' => 'El Seibo', 'country_id' => 65],
            ['name' => 'Miches', 'country_id' => 65],
            ['name' => 'Comendador', 'country_id' => 65],
            ['name' => 'Bánica', 'country_id' => 65],
            ['name' => 'El Llano', 'country_id' => 65],
            ['name' => 'Hondo Valle', 'country_id' => 65],
            ['name' => 'Juan Santiago', 'country_id' => 65],
            ['name' => 'Pedro Santana', 'country_id' => 65],
            ['name' => 'Moca', 'country_id' => 65],
            ['name' => 'Cayetano Germosén', 'country_id' => 65],
            ['name' => 'Gaspar Hernández', 'country_id' => 65],
            ['name' => 'Jamao al Norte', 'country_id' => 65],
            ['name' => 'Hato Mayor del Rey', 'country_id' => 65],
            ['name' => 'El Valle', 'country_id' => 65],
            ['name' => 'Sabana de la Mar', 'country_id' => 65],
            ['name' => 'Salcedo', 'country_id' => 65],
            ['name' => 'Tenares', 'country_id' => 65],
            ['name' => 'Villa Tapia', 'country_id' => 65],
            ['name' => 'Jimaní', 'country_id' => 65],
            ['name' => 'Cristóbal', 'country_id' => 65],
            ['name' => 'Duvergé', 'country_id' => 65],
            ['name' => 'La Descubierta', 'country_id' => 65],
            ['name' => 'Mella', 'country_id' => 65],
            ['name' => 'Postrer Río', 'country_id' => 65],
            ['name' => 'Higüey', 'country_id' => 65],
            ['name' => 'San Rafael del Yuma', 'country_id' => 65],
            ['name' => 'La Romana', 'country_id' => 65],
            ['name' => 'Guaymate', 'country_id' => 65],
            ['name' => 'Villa Hermosa', 'country_id' => 65],
            ['name' => 'La Concepción de La Vega', 'country_id' => 65],
            ['name' => 'Constanza', 'country_id' => 65],
            ['name' => 'Jarabacoa', 'country_id' => 65],
            ['name' => 'Jima Abajo', 'country_id' => 65],
            ['name' => 'Nagua', 'country_id' => 65],
            ['name' => 'Cabrera', 'country_id' => 65],
            ['name' => 'El Factor', 'country_id' => 65],
            ['name' => 'Río San Juan', 'country_id' => 65],
            ['name' => 'Bonao', 'country_id' => 65],
            ['name' => 'Maimón', 'country_id' => 65],
            ['name' => 'Piedra Blanca', 'country_id' => 65],
            ['name' => 'Montecristi', 'country_id' => 65],
            ['name' => 'Castañuela', 'country_id' => 65],
            ['name' => 'Guayubín', 'country_id' => 65],
            ['name' => 'Las Matas de Santa Cruz', 'country_id' => 65],
            ['name' => 'Pepillo Salcedo', 'country_id' => 65],
            ['name' => 'Villa Vásquez', 'country_id' => 65],
            ['name' => 'Monte Plata', 'country_id' => 65],
            ['name' => 'Bayaguana', 'country_id' => 65],
            ['name' => 'Peralvillo', 'country_id' => 65],
            ['name' => 'Sabana Grande de Boyá', 'country_id' => 65],
            ['name' => 'Yamasá', 'country_id' => 65],
            ['name' => 'Pedernales', 'country_id' => 65],
            ['name' => 'Oviedo', 'country_id' => 65],
            ['name' => 'Baní', 'country_id' => 65],
            ['name' => 'Nizao', 'country_id' => 65],
            ['name' => 'Puerto Plata', 'country_id' => 65],
            ['name' => 'Altamira', 'country_id' => 65],
            ['name' => 'Guananico', 'country_id' => 65],
            ['name' => 'Imbert', 'country_id' => 65],
            ['name' => 'Los Hidalgos', 'country_id' => 65],
            ['name' => 'Luperón', 'country_id' => 65],
            ['name' => 'Sosúa', 'country_id' => 65],
            ['name' => 'Villa Isabela', 'country_id' => 65],
            ['name' => 'Villa Montellano', 'country_id' => 65],
            ['name' => 'Samaná', 'country_id' => 65],
            ['name' => 'Las Terrenas', 'country_id' => 65],
            ['name' => 'Sánchez', 'country_id' => 65],
            ['name' => 'San Cristóbal', 'country_id' => 65],
            ['name' => 'Bajos de Haina', 'country_id' => 65],
            ['name' => 'Cambita Garabito', 'country_id' => 65],
            ['name' => 'Los Cacaos', 'country_id' => 65],
            ['name' => 'Sabana Grande de Palenque', 'country_id' => 65],
            ['name' => 'San Gregorio de Nigua', 'country_id' => 65],
            ['name' => 'Villa Altagracia', 'country_id' => 65],
            ['name' => 'Yaguate', 'country_id' => 65],
            ['name' => 'San José de Ocoa', 'country_id' => 65],
            ['name' => 'Rancho Arriba', 'country_id' => 65],
            ['name' => 'Sabana Larga', 'country_id' => 65],
            ['name' => 'San Juan de la Maguana', 'country_id' => 65],
            ['name' => 'Bohechío', 'country_id' => 65],
            ['name' => 'El Cercado', 'country_id' => 65],
            ['name' => 'Juan de Herrera', 'country_id' => 65],
            ['name' => 'Las Matas de Farfán', 'country_id' => 65],
            ['name' => 'Vallejuelo', 'country_id' => 65],
            ['name' => 'San Pedro de Macorís', 'country_id' => 65],
            ['name' => 'Consuelo', 'country_id' => 65],
            ['name' => 'Guayacanes', 'country_id' => 65],
            ['name' => 'Quisqueya', 'country_id' => 65],
            ['name' => 'Ramón Santana', 'country_id' => 65],
            ['name' => 'San José de Los Llanos', 'country_id' => 65],
            ['name' => 'Cotuí', 'country_id' => 65],
            ['name' => 'Cevicos', 'country_id' => 65],
            ['name' => 'Fantino', 'country_id' => 65],
            ['name' => 'La Mata', 'country_id' => 65],
            ['name' => 'Santiago', 'country_id' => 65],
            ['name' => 'Bisonó', 'country_id' => 65],
            ['name' => 'Jánico', 'country_id' => 65],
            ['name' => 'Licey al Medio', 'country_id' => 65],
            ['name' => 'Puñal', 'country_id' => 65],
            ['name' => 'Sabana Iglesia', 'country_id' => 65],
            ['name' => 'San José de las Matas', 'country_id' => 65],
            ['name' => 'Tamboril', 'country_id' => 65],
            ['name' => 'Villa González', 'country_id' => 65],
            ['name' => 'San Ignacio de Sabaneta', 'country_id' => 65],
            ['name' => 'Los Almácigos', 'country_id' => 65],
            ['name' => 'Monción', 'country_id' => 65],
            ['name' => 'Santo Domingo Este', 'country_id' => 65],
            ['name' => 'Boca Chica', 'country_id' => 65],
            ['name' => 'Los Alcarrizos', 'country_id' => 65],
            ['name' => 'Pedro Brand', 'country_id' => 65],
            ['name' => 'San Antonio de Guerra', 'country_id' => 65],
            ['name' => 'Santo Domingo Norte', 'country_id' => 65],
            ['name' => 'Santo Domingo Oeste', 'country_id' => 65],
            ['name' => 'Mao', 'country_id' => 65],
            ['name' => 'Esperanza', 'country_id' => 65],
            ['name' => 'Laguna Salada', 'country_id' => 65]
        ]);

        DB::table('cities')->update([
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
    }
}
